name: echo java version
description: Echo java version

inputs:
  java-version:
    description: 'Java version to use'
    required: true
    default: '17'

outputs:
  maven-version:
    description: 'The version of Maven used in the workflow'
    value: ${{ steps.maven_step.outputs.maven-version }}

runs:
  using: 'composite'  # ще є docker, node-16
  steps:
    - name: echo java version
      id: maven_step
      run: |
        echo "Java version is ${{ inputs.java-version }}"
        maven_version=$(mvn -v | head -1)
        echo "maven-version=$maven_version" >> $GITHUB_OUTPUT
      shell: bash


      # outputs призначені для передачі даних між кроками в рамках одного workflow.
      # В даному випадку, якщо потрібно передати якусь інформацію про версію Java або інші дані, можна встановити
      # значення в outputs і використовувати його в наступних кроках.