name: uses action example
on: 
  workflow_dispatch

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: ls -a
      - uses: actions/checkout@v6
      - name: List Files
        run: ls
      - name: run java
        run: | 
            cd src/main/java/fibonacci
            java FibonacciNumbers.java

          # https://github.com/actions/checkout
          # Розповісти про те що, за замовчуванням файлів, репозиторію нема на ранері. 
          # https://github.com/marketplace?type=actions
          # - action це скріпки розроблені іншими розробникамм для вирішення типових задач.