name: 4_workflow

on: 
  workflow_run:
    workflows: [firstTestWorkflow]
    types: 
      - completed

jobs: 
    step_1:
      runs-on: ubuntu-latest
      steps:
        - run: |
            pwd 
            ls
