name: workflow 10 # в github, context

on: workflow_dispatch

jobs: 
    step_1:
        runs-on: ubuntu-latest
        steps:
        - name: Context github
          run: echo '${{toJson(github)}}'
        - name: Context runner
          run:  echo '${{toJson(runner)}}'
        - name: Context job
          run: echo '${{toJson(job)}}'


# https://docs.github.com/en/actions/reference/workflows-and-actions/expressions
          # Коли я пишу ${{github}} це ознчає що я звертають до конкретного контексту,
          # який містить інформацію про репозиторій, гілку, коміт і т.д. Коли я пишу ${{runner}}
          # це означає що я звертають до контексту, який містить інформацію про середовище виконання,
          # на якому запускається джоба. Коли я пишу ${{job}} це означає що я звертають до контексту, який
          # містить інформацію про поточну джобу, її статус, ім'я і т.д.

          # все що написано в '${{}}' це синтаксис для звернення до контексту або змінної в GitHub Actions.
          # Це дозволяє отримувати доступ до різних даних і параметрів, які можуть бути корисними під час виконання джобів і кроків.
          # також тут можна викликати функції, наприклад toJson() для перетворення об'єкта в JSON-рядок, щоб краще його вивести в консолі.
          # ще можуть бути такі вирази як fronjson для перетворення JSON-рядка в об'єкт, або contains() для перевірки наявності певного елемента в масиві і т.д.