name: firstTestWorkflow
on: [push]

jobs:
  run_first_comant:
    runs-on: ubuntu-latest
    steps:
      - name: java version
        run: java -version
      - name: mvn version
        run: |  # або для того щоб запустити декілька команд одразу можемо написати через | 
          node -v
          npm -v
          dwfefesfsf

    #  для того щоб не запускати action можна написати [skip ci]
