name: secondFlow

on: 
  workflow_dispatch:
    inputs:
      title-custom:
        description: Type the title
        type: string
        required: true
        default: "Hello world"

jobs:
    run-comand:
        runs-on: ununtu-latest
        steps:
        - name: Output from title
          run: echo "Title ${{ inputs.title-custom}}"

