name: secondFlow

on: 
  workflow_dispatch:
    inputs:
      title-custom:
        description: Type the title
        type: string
        required: true
        default: "Hello world"

jobs:
  run-comand:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Title ${{ inputs.title-custom}}"
