name: vars_and_sevrets

on: [push]

jobs:
    first:
      runs-on: ubuntu-latest
      steps:
       - run: echo '${{vars.NAME}}'
       - run: echo '${{secrets.PASSWORD}}'
       - run: echo '${{secrets.GITHUB_TOKEN}}' # це автоматично створений токен, який новий під кожний ран, протухає після завершення джоби потрібен для доступу до поточного репо
