name: workflow 10 # виразі в github, context

on: 
    workflow_dispatch:

jobs: 
    step_1:
        runs-on: ubuntu-latest
        steps:
        - name: Context github
          run: |
            echo '${{toJson(github)}}'
        - name: Context runner
          run:  |
                echo '${{toJson(runner)}}'
        - name: Context job
          run: echo '${{toJson(job)}}'